package View;

import Controller.IActivity;
import javafx.event.ActionEvent;
import javafx.geometry.Insets;
import javafx.scene.Node;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class Introduction
{

    private IActivity controller;

    /**
     * <p>Linking controller to view and merely logging success of instantiation.</p>
     *
     *  @param controller the controller instance shared among views to manage the Activity model
     */
    public Introduction(IActivity controller)
    {
        this.controller = controller;
        System.out.println("Success Log: Introduction instance created");
    }

    /**
     * <p>A StackPane containing the Introduction GUI components is generated.</p>
     *
     * @return a StackPane containing the Introduction GUI components
     */
    public StackPane setup()
    {
        ImageView imageView = new ImageView();
        imageView.setImage(new Image(getClass().getResourceAsStream("/tree.jpg")));

        Label label = new Label("Carbon Impact Application");
        Label label2 = new Label("Track and measure your impact on the environment with this application");
        Button quit = new Button("Quit");
        Button memTest = new Button("memTest");
        setLabelStyle(label, true);
        setLabelStyle(label2, false);
        setButtonStyle(quit);
        setButtonStyle(memTest);
        quit.setOnAction(this::quitProgram);
        memTest.setOnAction(this::memTest);

        VBox mainColumn = new VBox(50, label, label2, quit, memTest);
        mainColumn.setPadding(new Insets(50, 20, 20, 20));

        return new StackPane(imageView, mainColumn);
    }

    /**
     * <p>Quit program when quit button is clicked.</p>
     *
     * @param e the event generated by the button being clicked
     */
    private void quitProgram(ActionEvent e)
    {
        final Node source = (Node) e.getSource();
        final Stage stage = (Stage) source.getScene().getWindow();
        stage.close();
    }

    private void memTest(ActionEvent e)
    {
        while (true)
        {
            controller.addActivity(10, "Hello World", 30, java.time.LocalDate.now());
        }
    }

    /**
     * <p>Applies fxml styling to the label passed through the parameters.</p>
     *
     * @param label the label in which pre-configured fxml styling will be applied
     */
    private void setLabelStyle(Label label, boolean big)
    {
        label.setStyle(
                "-fx-min-width: 100;" + /*"-fx-background-color: #F8B195;" +*/
                "-fx-padding: 5 5 5 5;" +
                "-fx-background-color: rgb(252,252,252);" +
                "-fx-font-size: " + (big ? "20px;" : "15px;")
        );
    }

    /**
     * <p>Applies fxml styling to the button passed through the parameters.</p>
     *
     * @param button the button in which pre-configured fxml styling will be applied
     */
    private void setButtonStyle(Button button)
    {
        button.setStyle(
                "-fx-min-width: 75;" + /*"-fx-background-color: #dc143c;" +*/
                "-fx-padding: 5 5 5 5;" +
                "-fx-font-size: 15px;" /*"-fx-text-fill: #ffffff;"*/
        );
    }

}
